name: adso
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pathlib
  - numpy
  - dask >= 2021.5
  - dask-ml
  - zarr
  - more-itertools
  - scikit-learn >= 0.22
  - nltk
  - sparse
  - dill
  - pyldavis
  - pandas
  - openpyxl
  - gensim
  - requests
  - umap-learn
  - hdbscan
  - modin-ray
  - python-igraph
  # only conda
  - graph-tool
  - topicmapping
  - mallet
  # pip
  - pip
  - pip:
      - tomotopy
      - numba-plsa>=0.0.2
      - ray[default]
