[tool.poetry]
name = "adso"
version = "0.0.1"
description = "A topic-modelling library"
authors = ["Michele 'TnTo' Ciruzzi <tnto@hotmail.it>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/TnTo/adso"

[tool.poetry.dependencies]
python = "^3.7"
pathlib = "^1.0.1"
nltk = "^3.5"
scipy = "^1.5.4"
sparse = "^0.11.2"
llvmlite = "^0.34.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
sphinx = "^3.2.1"
pytest-cov = "^2.10.1"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-import-order = "^0.18.1"
coverage = {version = "^5.3", extras = ["toml"]}
mypy = "^0.782"
flake8-annotations = "^2.4.1"
flake8-docstrings = "^1.5.0"
darglint = "^1.5.5"
xdoctest = "^0.15.0"
sphinx-autodoc-typehints = "^1.11.0"
ipykernel = "^5.3.4"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["example"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
